version: "3.8"

services: 
  nginx:
    image: nginx:1.19.5-alpine
    container_name: chat-app-nginx
    working_dir: /app
    volumes: 
      - ./app:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  
  php-fpm:
    build: ./docker/php-fpm
    container_name: chat-app-php-fpm
    working_dir: /app
    volumes: 
      - ./app:/app
      - ./docker/php-fpm/custom.ini:/etc/php/7.4/fpm/conf.d/custom.ini