version: "3.8"

volumes:
  db-data:

networks:
  chat-app-nw:

services:
  mysql:
    image: mysql:8.0.22
    container_name: chat-app-mysql
    working_dir: /app
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_dev
      MYSQL_DATABASE: chat_app_db
      MYSQL_USER: chat_app_usr
      MYSQL_PASSWORD: chat_app_pwd
    ports:
      - 8306:3306
    networks:
      - chat-app-nw

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - chat-app-nw

  webserver:
    image: nginx:1.19.5-alpine
    container_name: chat-app-webserver
    working_dir: /app
    volumes: 
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    networks:
      - chat-app-nw

  php-fpm:
    build: docker/php-fpm
    container_name: chat-app-php-fpm
    working_dir: /app
    volumes: 
      - .:/app
      - ./dockker/php-fpm/php-ini-override.ini:/etc/php7.4/fpm/conf.d/99-overrides.ini
    environment: 
      XDEBUG_CONFIG: "remote_host:127.0.0.1"
    networks:
      - chat-app-nw